element_test.exe: element_test.o p_element_string.o ../utilitaires/p_utilitaires.o
	gcc -o element_test.exe element_test.o p_element_string.o ../utilitaires/p_utilitaires.o

p_element_string.o: p_element_string.c
	gcc -c p_element_string.c

element_test.o: element_test.c
	gcc -c element_test.c