utilitaires_test.exe: utilitaires_test.o p_utilitaires.o
	gcc -o utilitaires_test.exe utilitaires_test.o p_utilitaires.o

p_utilitaires.o: p_utilitaires.c
	gcc -c p_utilitaires.c

utilitaires_test.o: utilitaires_test.c
	gcc -c utilitaires_test.c
	

